node{
	
 stage ('---------- build ---------------') {
 ([$class: 'GitSCM',
 branches: [[name: '*/master']],
 doGenerateSubmoduleConfigurations: false,
 extensions: [],
 submoduleCfg: [],
 userRemoteConfigs: [[url: 'https://github.com/anjali368/Playground']]])
}

 
 stage ('---------- build ---------------') {
         
	// for building java projects
        rtMaven.run pom: branch + '/' + projectToBuild + '/pom.xml', goals: 'clean install', buildInfo: buildInfo
 }
}
